# Generated by Django 4.2.7 on 2023-11-22 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0003_floor_branch_address_branch_closing_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=123)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('icon', models.CharField(max_length=250, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_category', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ('-id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=60, null=True)),
                ('video_url', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='item_thumbnail')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_user', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='food_items.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=130)),
                ('price', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_variants', to='food_items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
