# Generated by Django 4.2.7 on 2023-11-14 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Restaurant Name')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos')),
                ('address', models.CharField(max_length=350, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('payment_type', models.CharField(choices=[('PAY_FIRST', 'Pay First'), ('PAY_LATER', 'Pay Later')], verbose_name='Payment Type')),
                ('bin_number', models.CharField(max_length=40, verbose_name='Bin Number')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Branch Name')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_branch', to='restaurant.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
