# Generated by Django 4.2.7 on 2023-11-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('-id', 'restaurant'), 'verbose_name_plural': 'branches'},
        ),
    ]
