# Generated by Django 4.2.7 on 2023-11-16 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_alter_branch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Floor Name')),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'ordering': ('-id', 'branch'),
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_qr_image'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Floor Name')),
                ('table_type', models.CharField(blank=True, choices=[('RECTANGLE', 'Rectangle'), ('CIRCLE', 'Circle')], max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied')], max_length=120, null=True)),
                ('no_of_chairs', models.IntegerField(default=0)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_table', to='restaurant.floor')),
            ],
            options={
                'ordering': ('floor',),
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_floor', to='restaurant.branch'),
        ),
    ]
