# Generated by Django 4.2.7 on 2023-11-22 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
